CREATE TABLE DB2INST1.USER_TEST  ( 
    USERID        	INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1, CACHE 20) NOT NULL,    
    NAME          	VARCHAR(255) NOT NULL,
    EMAIL         	VARCHAR(255) NOT NULL,
    PASSWORD      	VARCHAR(40) NOT NULL,
    COUNTRY       	CHARACTER(2) NOT NULL,
    PHONE         	VARCHAR(255) NOT NULL,
    SEX           	VARCHAR(1),
    REGISTEREDDATE	TIMESTAMP NOT NULL,
    CONSTRAINT PK_USER_TEST PRIMARY KEY(USERID)
)
