
CREATE TABLE DB2INST1.user_test  ( 
    USERID        	INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1, CACHE 20) NOT NULL,   
    REGISTEREDDATE	TIMESTAMP NOT NULL,   
    NAME          	VARCHAR(255) NOT NULL,
    SURNAME       	VARCHAR(255) NOT NULL,
    EMAIL         	VARCHAR(255) NOT NULL,
    PASSWORD      	VARCHAR(40) NOT NULL,
    COUNTRY       	CHARACTER(2) NOT NULL,
    PHONE         	VARCHAR(255) NOT NULL,
    STREET        	VARCHAR(255),
    ZIP           	VARCHAR(64),
    CITY          	VARCHAR(64),    
    SEX           	VARCHAR(1),
   
    CONSTRAINT PK_USER_test PRIMARY KEY(USERID)
)
GO

